version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile2
    image: doc:first
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
